name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          version: "24.1.1"
