name: Test

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write

jobs:
  pytest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest --junitxml=pytest-junit.xml --cov=gsdl --cov-report=xml --cov-report=html
      - name: Upload JUnit XML
        uses: actions/upload-artifact@v4
        with:
          name: pytest-junit
          path: pytest-junit.xml
      - name: Upload Coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage
          path: coverage.xml
  junit-report:
    runs-on: ubuntu-22.04
    needs: pytest
    steps:
      - name: Download JUnit XML
        uses: actions/download-artifact@v4
        with:
          name: pytest-junit
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success()
        with:
          job_name: Test
          check_name: junit-test-report
          report_paths: pytest-junit.xml
  coverage-report:
    runs-on: ubuntu-22.04
    needs: pytest
    steps:
      - name: Download Coverage XML
        uses: actions/download-artifact@v4
        with:
          name: pytest-coverage
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
